# Generated by Django 3.2.9 on 2022-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0003_portfolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
